version: '3.2'

services:
  user_db:
    environment:
      - POSTGRES_DB=user_db

  db:
    environment:
      - POSTGRES_MULTIPLE_DATABASES=tkt_oodi,tkt_oodi_test

  backend:
    image: toska/oodikone2-backend:${TAG}
    build:
      cache_from:
        - toska/oodikone2-backend:trunk
        - toska/oodikone2-backend:staging
        - toska/oodikone2-backend:latest
    ports:
      - "9229:9229"
    environment:
      FRONT_URL: http://localhost:1337
      ANALYTICS_ADMINER_URL: http://localhost:5050/?pgsql=analytics_db&username=postgres

  frontend:
    image: toska/oodikone2-frontend:${TAG}
    build:
      args:
        BASE_PATH: /
        SENTRY_URL: ${SENTRY_URL}
        SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
        SENTRY_ORG: sentry
        SENTRY_PROJECT: oodifront
      cache_from:
        - toska/oodikone2-frontend:trunk
        - toska/oodikone2-frontend:staging
        - toska/oodikone2-frontend:latest
    ports:
      - "5000:5000"

  userservice:
    image: toska/oodikone2-userservice:${TAG}
    build:
      cache_from:
        - toska/oodikone2-userservice:trunk
        - toska/oodikone2-userservice:staging
        - toska/oodikone2-userservice:latest

  usageservice:
    image: toska/oodikone2-usageservice:${TAG}
    build:
      cache_from:
        - toska/oodikone2-usageservice:trunk
        - toska/oodikone2-usageservice:staging
        - toska/oodikone2-usageservice:latest

  updater_api:
    image: toska/updater_api:${TAG}
    build:
      cache_from:
        - toska/updater_api:trunk
        - toska/updater_api:staging
        - toska/updater_api:latest

  updater_writer:
    image: toska/updater_writer:${TAG}
    build:
      cache_from:
        - toska/updater_writer:trunk
        - toska/updater_writer:staging
        - toska/updater_writer:latest

  updater_scheduler:
    image: toska/updater_scheduler:${TAG}
    build:
      cache_from:
        - toska/updater_scheduler:trunk
        - toska/updater_scheduler:staging
        - toska/updater_scheduler:latest

  analytics:
    image: toska/oodikone2-analytics:${TAG}
    build:
      cache_from:
        - toska/oodikone2-analytics:trunk
        - toska/oodikone2-analytics:staging
        - toska/oodikone2-analytics:latest

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/log:/var/log/nginx/localhost.error_log
      - ./nginx/cache/:/etc/nginx/cache
    ports:
      -  1337:80
    depends_on:
      - frontend
      - backend
      - userservice
      - analytics
    container_name: nginx
