version: '3.2'

services:
  nats:
    volumes:
      - datastore-real:/datastore

  backend:
    environment:
      DB_URL: postgres://postgres@db:5432/tkt_oodi_real
      DB_URL_KONE: postgres://postgres@db_kone:5432/db_kone_real

  userservice:
    environment:
      DB_URL: postgres://postgres@user_db:5432/user_db_real

  analytics:
    environment:
      DB_URL: postgres://postgres@analytics_db:5432/analytics_db_real

  updater_writer:
    environment:
      DB_URL: postgres://postgres@db:5432/tkt_oodi_real
  updater_api:
    environment:
      - OODI_ADDR=https://oodikone.cs.helsinki.fi/oodi
      - TOKEN

  redis:
    volumes:
      - redis-data-real:/data

  scheduler_mongo:
    volumes:
      - mongodata-real:/data/db

volumes:
  datastore-real:
  redis-data-real:
  mongodata-real:
